### ISSUE TITLE
ide for cuda 

### ISSUE THREAD

**Issue by ccnankai** [pepe78/DeeperThought#1]
Thank you for your excellent work. 
I just started learning cuda, Is there is any good ide for this project? What tools should I use to optimize the cuda program?

**Comment by pepe78** [comment]
Good questions, so far no IDE for this project (to edit and link different layers). To write and optimize this cuda program I usually use Notepad++ when working on Windows (https://notepad-plus-plus.org/) or basic Text Editor when on Linux, which is there by default for Ubuntu.

If you want to optimize speed of cuda code, look at CUDA profilers:
https://docs.nvidia.com/cuda/profiler-users-guide/index.html

Hope this helps!
